FROM public.ecr.aws/lambda/python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}/requirements-lambda.txt

RUN pip install --upgrade pip \
    && pip install \
       --no-cache-dir \
       -r ${LAMBDA_TASK_ROOT}/requirements-lambda.txt \
       --target ${LAMBDA_TASK_ROOT}

COPY app ${LAMBDA_TASK_ROOT}/app
COPY data ${LAMBDA_TASK_ROOT}/data

CMD ["app.lambda_handler.handler"]